### ISSUE TITLE
Tests for the release of GN 3.3.0

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1030]
@ElenaGallo we are ready to run a full test of https://development.demo.geonode.org/ in view of the release of GN 3.3.0 next week.

Issues:

- mobile
  - [x]  [video](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6156164/scenario-snapshots/21581429/test-snapshots/29431160) https://github.com/geonode/geonode/issues/8322
  - [ ] **CAN'T REPRODUCE** [map TOC](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6156164/scenario-snapshots/21581430/test-snapshots/29431161) https://github.com/geonode/geonode/issues/8323
  - [x] [geostory](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6156164/scenario-snapshots/21581431/test-snapshots/29431162) https://github.com/geonode/geonode/issues/8324
  - [x] [dashboard](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6156164/scenario-snapshots/21581432/test-snapshots/29431163) https://github.com/GeoNode/geonode-mapstore-client/issues/580
- download 
  - [x] https://github.com/geonode/geonode-mapstore-client/issues/573
  - [x] https://github.com/geonode/geonode-mapstore-client/issues/572
- [x] [thumbnails cache](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6123685/scenario-snapshots/21479974/test-snapshots/29281110) https://github.com/geonode/geonode/issues/8312
- [x] add thumbnails from save as ([geostory](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6123719/scenario-snapshots/21480087/test-snapshots/29281223) and [dashbaord](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6123725/scenario-snapshots/21480110/test-snapshots/29281246))  https://github.com/GeoNode/geonode/issues/8325
- dashboards 
  - [x] [dashboards and legends](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6123723/scenario-snapshots/21480102/test-snapshots/29281238) https://github.com/geonode/geonode-mapstore-client/issues/579
  - [x] [interactions stop working after saving](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6123723/scenario-snapshots/21680501/test-snapshots/29578552) https://github.com/GeoNode/geonode-mapstore-client/issues/584
- [x] [add layer to existing](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6123697/scenario-snapshots/21499202/test-snapshots/29306206) map https://github.com/GeoNode/geonode-mapstore-client/issues/582
- [ ] [annotations not printed](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6123712/scenario-snapshots/21499555/test-snapshots/29306729)  https://github.com/GeoNode/geonode-mapstore-client/issues/593

**Comment by ElenaGallo** [comment]
@giohappy I added to Cucumber also the the test for [carousel, geocoding, mobile](https://github.com/geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV/issues/295#issuecomment-959783901). Some test failed for mobile ( see [here](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6156164) )

**Comment by giohappy** [comment]
@ElenaGallo I can't reproduce the problem with the download of mp3. See video below. How can I replicate it?
![export mp3 on mobile](https://user-images.githubusercontent.com/571129/140499778-8311e840-23fe-4dc0-9680-4a3cdc8c5c9e.gif)

**Comment by ElenaGallo** [comment]
@giohappy which test are you referring to?
For documents on mobile the problem is just this: 
* The video preview is not displayed correctly. Open the follows video document on mobile: https://development.demo.geonode.org/documents/77 and see picture attached below.ù

![video](https://user-images.githubusercontent.com/56537133/140502920-20eabdfc-7cb3-4049-bfde-24a2865e8a1b.gif)

**Comment by giohappy** [comment]
@ElenaGallo I'm referring to https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6156164/scenario-snapshots/21581429/test-snapshots/29431160 where, at the last step you marked:

![image](https://user-images.githubusercontent.com/571129/140503439-68f7daad-62f3-4e10-ae57-1cd0fb5956be.png)

**Comment by ElenaGallo** [comment]
ok, I didn't explain myself well. I always put a comment above the test when it fails
![xxxxx](https://user-images.githubusercontent.com/56537133/140503955-b533b5ed-a80a-4aec-9980-98500686edc0.png)
.

**Comment by giohappy** [comment]
ok, thx for the clarification @ElenaGallo. In that case you should split the tests. One for the visualization and one for the download.

**Comment by giohappy** [comment]
@ElenaGallo did you remove the layers for the [USA dashboard](https://development.demo.geonode.org/apps/14/view#/) that you were mentioning in the tests? The underlying layer seems to be removed. Can you please recreate it?

**Comment by giohappy** [comment]
@ElenaGallo I'm not able to reporodue the issue with the TOC of the map that you reported (https://github.com/geonode/geonode/issues/8323). What device and browser are you using?

**Comment by ElenaGallo** [comment]
@giohappy https://github.com/GeoNode/geonode/issues/8323#issuecomment-962074383

**Comment by giohappy** [comment]
@ElenaGallo in[ this failed test](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6123724/scenario-snapshots/21480106/test-snapshots/29281242) you report that widgets interactions are not working, and apparently you're saying that his happens when the map is viewed through shared link. However, it seems that interaction between widgets are not working in any case.
Do you have a test passed for widgets interactions?

**Comment by ElenaGallo** [comment]
@giohappy yes, you are right when the dashboard is saved the interactions don't work. I had tested an unsaved dashboard and in this case the interactions work, look at the following gif:

![dash](https://user-images.githubusercontent.com/56537133/141437741-990fbbe5-6104-4653-a8be-50b4a323132c.gif)

[Here](https://studio.cucumber.io/projects/291214/test-runs/605303/folder-snapshots/6123723/scenario-snapshots/21680501/test-snapshots/29578552) the new widget connection test that fails.

**Comment by giohappy** [comment]
@ElenaGallo The identify for dashboards are disabled on mobile (small screens) by design (see point 3 in https://github.com/geosolutions-it/MapStore2/issues/4150). Remove it from the tests for mobile.

**Comment by giohappy** [comment]
@ElenaGallo see the list of closed issues and rerun the tests for them.

**Comment by giohappy** [comment]
@ElenaGallo exlcuding the printing of annotations and the issue you reported with the TOC on mobile (we weren't able to reproduce it) all the rest should be fixed.
Please rerun the failed tests.

**Comment by ElenaGallo** [comment]
@giohappy All the tests reported on this epic now pass.
