### ISSUE TITLE
Prepare Release 4.0.2

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1505]
We want to take the opportunity of release 4.0.2 to define a flow and document it.
The tasks must be fulfilled:

- [X] Review the status of the issues connected to [milestone 4.0.2](https://github.com/GeoNode/geonode/milestone/32)
- [X] Review the [issues labeled for the branch](https://github.com/GeoNode/geonode/issues?q=is%3Aopen+is%3Aissue+label%3A4.0.x) the release will be cut from 4.0.x, in case we have missed critical issues from the target milestone
- [X] Review the [documentation](https://docs.google.com/document/d/1akINE7XYEL1MOxKty4rCJ_dJhhOTdB6m7y8DXbkjCBk) for the release of the sw packages (with the help of @afabiani), which should include 
    - creation of the tag 4.0.2 inside the GeoNode, GeoNode Client and GeoNode Project repositories
    - update the references inside `requirements.txt` to the 4.0.2 tags for the respective packages
    - creation of the changelogs:
      - Structure the changelog in sub lists (New features, Bug fixes, Upgrades, etc.)
      - For commits related to the same thing just keep the final one. Ex. bump upgrades should only report the latest upgrade
      - Take inspiration from GeoNode or, as an example, [Airflow's changelog](https://github.com/apache/airflow/releases/tag/2.5.0)
    - creation of the PyPi packages
- [X] Publishing of the release
- [X] Update the [Release Schedule](https://github.com/GeoNode/geonode/wiki/Release-schedule)
- [ ] Update stable demo instance to 4.0.2
   - update the tag inside the [Jenkins Job for stable demo](http://build.geosolutionsgroup.com/view/GeoNode/job/GeoNode/job/geonode-stable-demo/)
   - update https://geonode.org/
 - [ ] Prepare a blog page with the relevant news for this release. It should also mention that this will be the last release from branch `4.0.x`. The new development branch will be `4.1.x`.

Every release must be logged in the [same document](https://docs.google.com/document/d/1akINE7XYEL1MOxKty4rCJ_dJhhOTdB6m7y8DXbkjCBk/edit#heading=h.7pmynle5jn3v), and report the actions performed, including the packaging commands.
