### ISSUE TITLE
Centralized ElasticSearch-Kibana dashboards for GeoNode instances

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/geonode#339]
We want to have a centralized management of analytics data coming from many GeoNode instances. Those data will be exposed through Kibana dashboards.

So we have to:
- [x] make available the ELK stack on a server
- [x] make available an admin console/interface on the server
- [x] define how to extend GeoNode monitoring plugin to send message to Centralized Dashboard  #345
- [x] define how to secure communication between GeoNode instances and Centralized Dashboard #344
- [x] define what data to send/receive, see #342 
- [x] define (#343) and implement the REST APIs that GeoNode instances will consume to send their data (json `GELF` via `TCP`/`HTTPS`)
- [x] Extend GeoNode monitoring plugin to send events to the centralized dashboard

Further specs:
- each GeoNode instance which want to use the service will have an ID
- whenever a GeoNode instance wants to send its data, it must include an auth token in the request (only authorized GeoNodes can access the service)
- two kind of Kibana dashboards are needed:
    - 1 for each GeoNode instance
    - 1 for all the GeoNode instances
