### ISSUE TITLE
Introduce new query parameters to request.users metric_data

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode#353]
We should extend query parameters of request.users metric_data to get following scenarios:

- [ ] #349 Get unique visitors count
- [ ] #350 Get anonymous sessions count
- [ ] #351 Get unique visitors list

### Current Implementation
Request
```
/monitoring/api/metric_data/request.users/
 ?valid_from=2019-01-01+00:00:00
 &valid_to=2019-12-31+23:59:59
 &interval=31536000
 &resource_type=layer
```

Response

```
{
    "data": {
        "input_valid_from": "2019-01-01T00:00:00-06:00",
        "input_valid_to": "2019-12-31T23:59:59-06:00",
        "data": [
            {
                "valid_from": "2019-01-01T00:00:00-06:00",
                "data": [
                    {
                        "samples_count": 42,
                        "val": "42.0000",
                        "min": "1.0000",
                        "max": "2.0000",
                        "sum": "42.0000",
                        "label": "944da909ed831522d14710cdef6d7dbec5f59a0cdef6d7dbec",
                        "user": "admin",
                        "metric_count": 27
                    },
                    {
                        "samples_count": 33,
                        "val": "33.0000",
                        "min": "1.0000",
                        "max": "4.0000",
                        "sum": "33.0000",
                        "label": "55717540a8c337a4943929a473aeb2e9c07ff4a0af00bcd66c",
                        "user": "admin",
                        "metric_count": 18
                    },
                    {
                        "samples_count": 11,
                        "val": "11.0000",
                        "min": "1.0000",
                        "max": "4.0000",
                        "sum": "11.0000",
                        "label": "221f5cc0e3d8bf56f539f1f632ae488d1840d8306e7a0fsda",
                        "user": "user",
                        "metric_count": 7
                    },
                    {
                        "samples_count": 11,
                        "val": "11.0000",
                        "min": "1.0000",
                        "max": "2.0000",
                        "sum": "11.0000",
                        "label": "c71497335a5709f62214afa4a31df690640329eqqqaswddwd",
                        "user": "AnonymousUser",
                        "metric_count": 7
                    },
                    {
                        "samples_count": 9,
                        "val": "9.0000",
                        "min": "1.0000",
                        "max": "2.0000",
                        "sum": "9.0000",
                        "label": "f16c1475ff9065f94cf2accebd4b292040dd42af438fe410s",
                        "user": "AnonymousUser",
                        "metric_count": 8
                    }
                ],
                "valid_to": "2020-01-01T00:00:00-06:00"
            }
        ],
        "metric": "request.users",
        "interval": 31536000.0,
        "type": "value",
        "axis_label": "Count",
        "label": null
    }
}
```

### Get unique visitors count

Request

add `group_by`=`unique_visitors`
based on example below it should return a val equal to 3 (admin + user + AnonymousUser)

```
/monitoring/api/metric_data/request.users/
 ?valid_from=2019-01-01+00:00:00
 &valid_to=2019-12-31+23:59:59
 &interval=31536000
 &resource_type=layer
 &group_by=unique_visitors
```

Response

```
{
    "data": {
        "input_valid_from": "2019-01-01T00:00:00-06:00",
        "input_valid_to": "2019-12-31T23:59:59-06:00",
        "data": [
            {
                "valid_from": "2019-01-01T00:00:00-06:00",
                "data": [
                    {
                        "samples_count": 42,
                        "val": 3,
                        "min": "1.0000",
                        "max": "2.0000",
                        "sum": "42.0000",
                        "metric_count": 27
                    }
                ],
                "valid_to": "2020-01-01T00:00:00-06:00"
            }
        ],
        "metric": "request.users",
        "interval": 31536000.0,
        "type": "value",
        "axis_label": "Count",
        "label": null
    }
}
```

### Get anonymous sessions count

Request

add `user`=`AnonymousUser` to filter on user equal to AnonymousUser

combined with `group_by`=`label` (label represents sessions)

based on example below it should return a val equal to 2 (AnonymousUser * 2)

```
/monitoring/api/metric_data/request.users/
 ?valid_from=2019-01-01+00:00:00
 &valid_to=2019-12-31+23:59:59
 &interval=31536000
 &resource_type=layer
 &group_by=label
 &user=AnonymousUser
```

Response

```
{
    "data": {
        "input_valid_from": "2019-01-01T00:00:00-06:00",
        "input_valid_to": "2019-12-31T23:59:59-06:00",
        "data": [
            {
                "valid_from": "2019-01-01T00:00:00-06:00",
                "data": [
                    {
                        "samples_count": 42,
                        "val": 2,
                        "min": "1.0000",
                        "max": "2.0000",
                        "sum": "42.0000",
                        "metric_count": 27
                    }
                ],
                "valid_to": "2020-01-01T00:00:00-06:00"
            }
        ],
        "metric": "request.users",
        "interval": 31536000.0,
        "type": "value",
        "axis_label": "Count",
        "label": null
    }
}
```

### Get unique visitors list
Request

add `group_by`=`user`

should the val contain the sum of sessions visits or sessions count?

based on example below it should return a val equal to:
if sessions visits
- admin val 42 + 33 -> 75
- user val 11
- AnonymousUser val 11 + 9 -> 20

if sessions count (I think should be this one)
- admin val 2 (admin * 2)
- user val 1 (user * 1)
- AnonymousUser val 2  (AnonymousUser * 1)

```
/monitoring/api/metric_data/request.users/
 ?valid_from=2019-01-01+00:00:00
 &valid_to=2019-12-31+23:59:59
 &interval=31536000
 &resource_type=layer
 &group_by=user
```

Response

```
{
    "data": {
        "input_valid_from": "2019-01-01T00:00:00-06:00",
        "input_valid_to": "2019-12-31T23:59:59-06:00",
        "data": [
            {
                "valid_from": "2019-01-01T00:00:00-06:00",
                "data": [
                    {
                        "samples_count": 42,
                        "val": 2,
                        "min": "1.0000",
                        "max": "2.0000",
                        "sum": "42.0000",
                        "user": "admin",
                        "metric_count": 27
                    },
                    {
                        "samples_count": 11,
                        "val": 2,
                        "min": "1.0000",
                        "max": "2.0000",
                        "sum": "11.0000",
                        "user": "AnonymousUser",
                        "metric_count": 7
                    },
                    {
                        "samples_count": 11,
                        "val": 1,
                        "min": "1.0000",
                        "max": "4.0000",
                        "sum": "11.0000",
                        "user": "user",
                        "metric_count": 7
                    }
                ],
                "valid_to": "2020-01-01T00:00:00-06:00"
            }
        ],
        "metric": "request.users",
        "interval": 31536000.0,
        "type": "value",
        "axis_label": "Count",
        "label": null
    }
}
```

**Comment by gioscarda** [comment]
Resolved.
This issue can be closed.
