### ISSUE TITLE
Finalize centralized monitoring/analytics

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/geonode#376]
In order to finalize the centralized monitoring/analytics server implementation we have to:
- [ ] install, configure and test ElastAlert (ref. #374 )
- [ ] install, configure and test Heartbeat (ref. #373 )
- [ ] finalize the monitoring app extension on the GeoNode side (ref. #369, #368, #371, #372 , #363)
- [ ] investigate on how GeoNode retrieve data from GeoServer and if this process stops when disabling monitoring on the GeoNode side (ref. #375 )
