### ISSUE TITLE
GeoNode 2.10.1: Release

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#382]
# TODO List:
 - [ ] Fix: https://github.com/GeoNode/geonode/pull/5217
 - [ ] Fix: https://github.com/GeoNode/geonode/pull/5198
 - [ ] Check if some docs are missing and update them
 - [ ] Update Docker Images and test docker deployments
 - [ ] Tag the release and push the Pypi wheels
 - [ ] Branch master to 3.0
 - [ ] Advertise the community
