### ISSUE TITLE
Backend tasks to complete for the new GN home page

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#557]
please @allyoucanmap review the list below. @afabiani is ready to workf on the issues with higher priority. I would say let's do our best in 1 day.

**HIGH PRIORITY**
- [x] polymorphic_ctype: we need a way to obtain the labels (layer, document, etc.) associated with the polymorphic type ids, otherwise MapStore will show the ids for the filtering options by resource type
- [x] retrieve list of filter options (categories, keywords, regions, ...)
- [x] API v2 filter by extent
- [x] synchronize language selection between frontend and backend (cookie based?)

MEDIUM PRIORITY
- [x] API v2 featured maps

**Comment by allyoucanmap** [comment]
> [ ]  polymorphic_ctype: we need a way to obtain the labels (layer, document, etc.) associated with the polymorphic type ids, otherwise MapStore will show the ids for the filtering options by resource type

Currently I have the same issue with categories because I'm filtering with the uniq name instead of label. We should solve this issue at the same way for both kind of filters.

> [ ] retrieve list of filter options (categories, keywords, regions, ...)

I'm using the api V1, let me know if we want to move to the V2 wit hnew endpoints.

> [ ] API v2 filter by extent

I'm sending a query with this structure

```
?extent=minx,miny,maxx,maxy
?extent=minx1,miny1,maxx1,maxy1,minx2,miny2,maxx2,maxy2 (cross dateline double bbox)
```


> [ ] synchronize language selection between frontend and backend (cookie based?)

probably I don't need update on the backend for this point, I should be able to use /i18n/setlang/ from the v1 api

```
export const setLanguage = (languageCode) => {
    const csrfMiddlewareToken = cookies.get('csrftoken');
    return axios.post('/i18n/setlang/', `csrfmiddlewaretoken=${csrfMiddlewareToken}&language=${languageCode}`);
};
```

and inject the variable in the template
```
languageCode: '{{ LANGUAGE_CODE }}'
```

@afabiani let me know if you prefer to move also this endpoint to the V2, in the meanwhile I'm using the existing one to complete a workflow.

**Comment by afabiani** [comment]
@allyoucanmap `languageCode` option is ok, let's keep this one.

**Comment by allyoucanmap** [comment]
Others endpoints used by home spa:

- `/base/autocomplete_response`
- `/i18n/setlang/`

- `/api/o/v4/userinfo`
- `/api/categories`
- `/api/keywords`
- `/api/regions`
- `/api/owners`

We should decide which should be migrated to V2

**Comment by afabiani** [comment]
## Work Plan
To complete a first working implementation:

 - [ ] Merge api v2 and spa branches on master (GeoNode, adapter and mapstore-client)
 - [ ] Create an endpoint to retrieve the `polymorphic_ctype` labels
 - [ ] Check the list of api v1 filters and see which one/if must be converted to v2
 - [ ] Double check/create endpoint to filter by extent and align the client accordingly

**Comment by giohappy** [comment]
@afabiani give me an estimate for each task.

**Comment by afabiani** [comment]
@giohappy I have updated the list above

**Comment by giohappy** [comment]
ok, let's move on quickly. I've created the issues, please add any additional detail there if needed

**Comment by afabiani** [comment]
@giohappy @allyoucanmap I'm done for now, let's sync back as soon as possible.

@giohappy can you elaborate a bit this sentence?
"API v2 featured maps"
what is th expected behavior?

**Comment by afabiani** [comment]
@allyoucanmap @giohappy after having spoken to Stefano, those are the remaining things to do for now (my side):

 - [ ] Prepare an endpoint to return the available "reource_types" `/api/v2/base_resources/resource_types`
 - [ ] Prepare an endpoint to return the available "featured maps" `/api/v2/maps/featured`

**Comment by afabiani** [comment]
@giohappy @allyoucanmap so far I have pushed to `rest_api_v2_geonode_apps` branch the following changes:

 - [x] Renamed `/api/v2/base_resources` endpoint to `/api/v2/resources`
 - [x] Added `/api/v2/resources/resource_types`; returns the list of available `resource_types` (aka `polymorphic_ctype` labels)
 - [x] Added `/api/v2/resources/featured`
 - [x] Added `/api/v2/resources/published`
 - [x] Added `/api/v2/resources/approved`
 - [x] Added Test Suite for GeoApps and improved Test cases for the other V2 APIs endpoints

**Comment by giohappy** [comment]
Mitico!
